class Residence < Enumeration
  self.add_item(:BAXTER_HALL, 'Baxter Hall')
  self.add_item(:CLARINUS_VILLAGE, 'Clarinus Village')
  self.add_item(:COLLEGE_HOUSE, 'College House')
  self.add_item(:FOREST_HILL, 'Forest Hill')
  self.add_item(:FULLER_HALL, 'Fuller Hall')
  self.add_item(:GLENRES, 'GlenRes')
  self.add_item(:GRACA_MACHEL_HALL, 'Graca Machel Hall')
  self.add_item(:GROOTE_SCHUUR, 'Groote Schuur')
  self.add_item(:KILINDINI, 'Kilindini')
  self.add_item(:KOPANO, 'Kopano')
  self.add_item(:LEO_MARQUARD, 'Leo Marquard')
  self.add_item(:LIESBEECK_GARDENS, 'Liesbeeck Gardens')
  self.add_item(:MEDICAL_RESIDENCE, 'Medical Residence')
  self.add_item(:OBZ_SQUARE, 'Obz Square')
  self.add_item(:ROCHESTER_HOUSE, 'Rochester House')
  self.add_item(:SMUTS_HALL, 'Smuts Hall')
  self.add_item(:THE_WOOLSACK, 'The Woolsack')
  self.add_item(:TUGWELL_HALL, 'Tugwell Hall')
  self.add_item(:UNIVERSITY_HOUSE, 'University House')
  self.add_item(:VARIETAS, 'Varietas')
end